### PR TITLE
More typos

### PR DESCRIPTION
**Pull request by ChrisKeefe**
Takes most of the commits from #489, leaving that PR focused on `artifact-api` changes.

### CODE REVIEW

**Comment by thermokarst** [comment]
The artifact-api changes should stay in 489, right?

**Comment by ChrisKeefe** [comment]
Artifact-api changes have been removed. This should be good for review.

**Comment by ChrisKeefe** [comment]
@Oddant1, would you like to give these changes a look?

**Comment by thermokarst** [comment]
@Oddant1, you don't need to review anything in particular here - the entire changeset in #488 will be reviewed as a whole.

On a more procedural note, @ChrisKeefe, I think in future situations like this, maybe just checking with the original author to see if its okay to push commits straight up to their branch is the right way to go - I think the PR approach here is just making a bit more work than necessary.

**Pull request merged**
